GET http://localhost:3000/admin

###

POST http://localhost:3000/authorization
Content-Type: application/json

{
    "email": "test@test.se",
    "password": "test123"
}

###

POST http://localhost:3000/add
Content-Type: application/json

{
    "email": "hej@hej.se",
    "password": "hej666"
}

###
GET http://localhost:3000/user/getloggedinuser

###

POST http://localhost:3000/authorization/admin
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

