GET http://localhost:3000/admin

###

POST http://localhost:3000/authorization
Content-Type: application/json

{
    "email": "vov@hund.se",
    "password": "kissapåstolpe"
}

###

POST http://localhost:3000/add
Content-Type: application/json

{
    "email": "vov@hund.se",
    "password": "kissapåstolpe"
}

###
GET http://localhost:3000/user/getloggedinuser

###

POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

###

POST http://localhost:3000/userdata
Content-Type: application/json

{
    "userId" : "6293e5bad5e825904be5fddf"
}

###

POST http://localhost:3000/newslettersettings
Content-Type: application/json

{
    "userId" : "6293b2429df07879c48cabb3",
    "newsletter" : "false"
}

